import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="justify-items-center p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
